# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json
backend:
  name: github
  repo: yasi-artisan/white-on-white
  branch: main

media_folder: /public/media
public_folder: /media

media_libraries:
  default:
    config:
      max_file_size: 1024000 # default: Infinity
      slugify_filename: true # default: false
  cloudinary:
    config:
      cloud_name: dgpqqcuyf
      api_key: 447547158277739

collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: /src/data/pages
    extension: mdx
    path: '{{folder}}/{{slug}}'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: richtext, required: false, buttons: [bold, italic], modes: [rich_text], editor_components:[] }
      - { label: Draft, name: draft, widget: boolean, default: true }
      - { label: Body, name: body, widget: richtext, required: false }
      # - { label: Path, name: path, widget: string,   sanitize_replacement: '-', trim: true, lowercase: true },
      - { label: Folder, name: folder, widget: string, required: false, hint: 'Use folder to organize pages.'}
      - {
          label: Cover Image,
          name: cover_image,
          widget: image,
          media_library: cloudinary,
          required: false,
        }
      - { name: gallery,
          label: Gallery, 
          widget: image, 
          multiple: true,
          required: false,
        }  

singletons:
  - name: settings
    label: Site Settings
    file: /src/data/settings.yaml
    fields:
      - { label: Site Name, name: siteName }
      - name: menuLinks
        label: Menu Links
        widget: list
        fields:
          - name: label
            label: Label
            widget: string
          - name: url
            label: URL
            widget: string
      - name: footerLinks
        label: Footer Links
        widget: list
        fields:
          - name: label
            label: Label
            widget: string
          - name: url
            label: URL
            widget: string
      - name: landingPageSettings
        label: Landing Page Settings
        widget: object
        fields:
          - name: links
            label: Links
            widget: list
            fields:
              - name: label
                label: Label
                widget: string
              - name: href
                label: URL
                widget: string
              - name: shape
                label: Shape
                widget: select
                options:
                  - ostrich
                  - carmolek
                  - squirrel
                  - pigeon
                  - rabbit
