# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json
backend:
  name: github
  repo: yasi-artisan/white-on-white
  branch: main

media_folder: /public/media
public_folder: /media

media_libraries:
  default:
    config:
      max_file_size: 1024000 # default: Infinity
      slugify_filename: true # default: false
  cloudinary:
    config:
      cloud_name: dgpqqcuyf
      api_key: 447547158277739

collections:
  - name: pages
    label: Pages
    label_singular: Post
    folder: /src/content/pages
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, type: date }
      - { label: Body, name: body, widget: richtext }
      - {
          label: Cover Image,
          name: cover_image,
          widget: image,
          media_library: cloudinary,
        }

singletons:
  - name: settings
    label: Site Settings
    file: content/settings.yaml
    fields:
      - { label: Site Name, name: site_name }
      - name: menu-links
        label: Menu Links
        widget: list
        fields:
          - name: label
            label: Label
            widget: string
          - name: url
            label: URL
            widget: string
